# Generated by Django 5.2.3 on 2025-06-11 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_ciudad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciudad',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='ciudad',
            old_name='population',
            new_name='poblacion',
        ),
    ]
